# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('slug', models.CharField(blank=True, max_length=128, unique=True)),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_on', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('hits', models.IntegerField(verbose_name='点击量')),
            ],
            options={
                'ordering': ['-hits', 'create_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('content', models.TextField(max_length=500, verbose_name='评论')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='website.Article')),
            ],
            options={
                'ordering': ['create_on'],
            },
        ),
    ]
