# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='website.UserProfile'),
        ),
    ]
