# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20161016_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='users',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='video',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='users',
            field=models.ManyToManyField(related_name='video', to='website.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
