# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20161016_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='man', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
