# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.CharField(blank=True, max_length=128, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('hits', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['-hits', 'create_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('content', models.TextField(blank=True, max_length=500, verbose_name='内容')),
                ('create_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['create_on'],
            },
        ),
    ]
